language: java
jdk:
- openjdk7
services:
- postgresql
before_install:
- openssl aes-256-cbc -K $encrypted_d4933bd8b822_key -iv $encrypted_d4933bd8b822_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz
- mkdir -p lib
install:
- echo "Build started"
- mvn clean install
#deploy to GAE
- gcloud auth activate-service-account --key-file client-secret.json
- gcloud compute ssh --zone ZONE INSTANCE -- 'mvn appengine:deploy'

#deploy:
#  provider: gae
#  keyfile: client-secret.json
#  project: high-ace-181518
#  config: src/main/appengine/app.yaml

#script:
#e2e test scripts goes here
after_script:
- echo "Build completed"