language: java
jdk:
- openjdk7
services:
- postgresql
install:
- gcloud config set project swe573
script:
- echo "Build started"
- mvn clean install
after_script:
- echo "Build completed"
dd:
- openssl aes-256-cbc -K $encrypted_d93e3b822ed8_key -iv $encrypted_d93e3b822ed8_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
