language: java
jdk:
- openjdk7
services:
- postgresql
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
before_install:
- openssl aes-256-cbc -K $encrypted_d4933bd8b822_key -iv $encrypted_d4933bd8b822_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz
- mkdir -p lib
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
install:
- gcloud auth activate-service-account --key-file client-secret.json
- gcloud config set project swe573
script:
- echo "Build started"
- mvn clean install
- gcloud components update preview app
after_script:
- echo "Build completed"
