/*
 * Etkinlik.io API
 * Tüm etkinlikleri toplamayı, kategorize etmeyi ve ilgili kişilere duyurmayı amaç edinmiş bir projedir. Bu API dokümantasyonu ile bir çok kaynaktan ve organizatörden beslenerek bir araya getirdiğimiz etkinlik içeriğine entegre olarak uygulamalar geliştirebilirsiniz. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * EtkinlikOzellik
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-29T05:46:48.775Z")
public class EtkinlikOzellik {
  @SerializedName("telefon")
  private String telefon = null;

  @SerializedName("mail")
  private String mail = null;

  @SerializedName("facebook")
  private String facebook = null;

  @SerializedName("twitter")
  private String twitter = null;

  @SerializedName("hashtag")
  private String hashtag = null;

  @SerializedName("websitesi")
  private String websitesi = null;

  @SerializedName("canliyayin")
  private String canliyayin = null;

  @SerializedName("android")
  private String android = null;

  @SerializedName("ios")
  private String ios = null;

  public EtkinlikOzellik telefon(String telefon) {
    this.telefon = telefon;
    return this;
  }

   /**
   * Etkinlik için tanımlanmış telefon bilgisi.
   * @return telefon
  **/
  @ApiModelProperty(value = "Etkinlik için tanımlanmış telefon bilgisi.")
  public String getTelefon() {
    return telefon;
  }

  public void setTelefon(String telefon) {
    this.telefon = telefon;
  }

  public EtkinlikOzellik mail(String mail) {
    this.mail = mail;
    return this;
  }

   /**
   * Etkinlik için tanımlanmış mail bilgisi.,
   * @return mail
  **/
  @ApiModelProperty(value = "Etkinlik için tanımlanmış mail bilgisi.,")
  public String getMail() {
    return mail;
  }

  public void setMail(String mail) {
    this.mail = mail;
  }

  public EtkinlikOzellik facebook(String facebook) {
    this.facebook = facebook;
    return this;
  }

   /**
   * Etkinlik için tanımlanmış facebook bilgisi.
   * @return facebook
  **/
  @ApiModelProperty(value = "Etkinlik için tanımlanmış facebook bilgisi.")
  public String getFacebook() {
    return facebook;
  }

  public void setFacebook(String facebook) {
    this.facebook = facebook;
  }

  public EtkinlikOzellik twitter(String twitter) {
    this.twitter = twitter;
    return this;
  }

   /**
   * Etkinlik için tanımlanmış twitter bilgisi.
   * @return twitter
  **/
  @ApiModelProperty(value = "Etkinlik için tanımlanmış twitter bilgisi.")
  public String getTwitter() {
    return twitter;
  }

  public void setTwitter(String twitter) {
    this.twitter = twitter;
  }

  public EtkinlikOzellik hashtag(String hashtag) {
    this.hashtag = hashtag;
    return this;
  }

   /**
   * Etkinlik için tanımlanmış hashtag bilgisi.
   * @return hashtag
  **/
  @ApiModelProperty(value = "Etkinlik için tanımlanmış hashtag bilgisi.")
  public String getHashtag() {
    return hashtag;
  }

  public void setHashtag(String hashtag) {
    this.hashtag = hashtag;
  }

  public EtkinlikOzellik websitesi(String websitesi) {
    this.websitesi = websitesi;
    return this;
  }

   /**
   * Etkinlik için tanımlanmış websitesi url bilgisi.
   * @return websitesi
  **/
  @ApiModelProperty(value = "Etkinlik için tanımlanmış websitesi url bilgisi.")
  public String getWebsitesi() {
    return websitesi;
  }

  public void setWebsitesi(String websitesi) {
    this.websitesi = websitesi;
  }

  public EtkinlikOzellik canliyayin(String canliyayin) {
    this.canliyayin = canliyayin;
    return this;
  }

   /**
   * Etkinlik için tanımlanmış canlı yayın url bilgisi.
   * @return canliyayin
  **/
  @ApiModelProperty(value = "Etkinlik için tanımlanmış canlı yayın url bilgisi.")
  public String getCanliyayin() {
    return canliyayin;
  }

  public void setCanliyayin(String canliyayin) {
    this.canliyayin = canliyayin;
  }

  public EtkinlikOzellik android(String android) {
    this.android = android;
    return this;
  }

   /**
   * Etkinlik için tanımlanmış android url bilgisi.
   * @return android
  **/
  @ApiModelProperty(value = "Etkinlik için tanımlanmış android url bilgisi.")
  public String getAndroid() {
    return android;
  }

  public void setAndroid(String android) {
    this.android = android;
  }

  public EtkinlikOzellik ios(String ios) {
    this.ios = ios;
    return this;
  }

   /**
   * Etkinlik için tanımlanmış ios url bilgisi.
   * @return ios
  **/
  @ApiModelProperty(value = "Etkinlik için tanımlanmış ios url bilgisi.")
  public String getIos() {
    return ios;
  }

  public void setIos(String ios) {
    this.ios = ios;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EtkinlikOzellik etkinlikOzellik = (EtkinlikOzellik) o;
    return Objects.equals(this.telefon, etkinlikOzellik.telefon) &&
        Objects.equals(this.mail, etkinlikOzellik.mail) &&
        Objects.equals(this.facebook, etkinlikOzellik.facebook) &&
        Objects.equals(this.twitter, etkinlikOzellik.twitter) &&
        Objects.equals(this.hashtag, etkinlikOzellik.hashtag) &&
        Objects.equals(this.websitesi, etkinlikOzellik.websitesi) &&
        Objects.equals(this.canliyayin, etkinlikOzellik.canliyayin) &&
        Objects.equals(this.android, etkinlikOzellik.android) &&
        Objects.equals(this.ios, etkinlikOzellik.ios);
  }

  @Override
  public int hashCode() {
    return Objects.hash(telefon, mail, facebook, twitter, hashtag, websitesi, canliyayin, android, ios);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EtkinlikOzellik {\n");
    
    sb.append("    telefon: ").append(toIndentedString(telefon)).append("\n");
    sb.append("    mail: ").append(toIndentedString(mail)).append("\n");
    sb.append("    facebook: ").append(toIndentedString(facebook)).append("\n");
    sb.append("    twitter: ").append(toIndentedString(twitter)).append("\n");
    sb.append("    hashtag: ").append(toIndentedString(hashtag)).append("\n");
    sb.append("    websitesi: ").append(toIndentedString(websitesi)).append("\n");
    sb.append("    canliyayin: ").append(toIndentedString(canliyayin)).append("\n");
    sb.append("    android: ").append(toIndentedString(android)).append("\n");
    sb.append("    ios: ").append(toIndentedString(ios)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

