/*
 * Etkinlik.io API
 * Tüm etkinlikleri toplamayı, kategorize etmeyi ve ilgili kişilere duyurmayı amaç edinmiş bir projedir. Bu API dokümantasyonu ile bir çok kaynaktan ve organizatörden beslenerek bir araya getirdiğimiz etkinlik içeriğine entegre olarak uygulamalar geliştirebilirsiniz. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Etiket;
import io.swagger.client.model.EtkinlikOzellik;
import io.swagger.client.model.Kategori;
import io.swagger.client.model.Mekan;
import io.swagger.client.model.Tur;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * Etkinlik
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-29T05:46:48.775Z")
public class Etkinlik {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("adi")
  private String adi = null;

  @SerializedName("radi")
  private String radi = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("icerik")
  private String icerik = null;

  @SerializedName("baslangic")
  private DateTime baslangic = null;

  @SerializedName("bitis")
  private DateTime bitis = null;

  @SerializedName("ucretli_mi")
  private Boolean ucretliMi = null;

  @SerializedName("afis_url")
  private String afisUrl = null;

  @SerializedName("durum")
  private Integer durum = null;

  @SerializedName("ozellik")
  private EtkinlikOzellik ozellik = null;

  @SerializedName("tur")
  private Tur tur = null;

  @SerializedName("kategori")
  private Kategori kategori = null;

  @SerializedName("mekan")
  private Mekan mekan = null;

  @SerializedName("etiketler")
  private List<Etiket> etiketler = null;

  public Etkinlik id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Etkinlik id bilgisi.
   * @return id
  **/
  @ApiModelProperty(value = "Etkinlik id bilgisi.")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Etkinlik adi(String adi) {
    this.adi = adi;
    return this;
  }

   /**
   * Etkinliğin adı bilgisi.
   * @return adi
  **/
  @ApiModelProperty(value = "Etkinliğin adı bilgisi.")
  public String getAdi() {
    return adi;
  }

  public void setAdi(String adi) {
    this.adi = adi;
  }

  public Etkinlik radi(String radi) {
    this.radi = radi;
    return this;
  }

   /**
   * Etkinliğin radı (slug) bilgisi.
   * @return radi
  **/
  @ApiModelProperty(value = "Etkinliğin radı (slug) bilgisi.")
  public String getRadi() {
    return radi;
  }

  public void setRadi(String radi) {
    this.radi = radi;
  }

  public Etkinlik url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Etkinliğin url bilgisi.
   * @return url
  **/
  @ApiModelProperty(value = "Etkinliğin url bilgisi.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Etkinlik icerik(String icerik) {
    this.icerik = icerik;
    return this;
  }

   /**
   * Etkinliğin içerik bilgisi. Etkinlik hakkında detalı bilgi içeren kısım. 
   * @return icerik
  **/
  @ApiModelProperty(value = "Etkinliğin içerik bilgisi. Etkinlik hakkında detalı bilgi içeren kısım. ")
  public String getIcerik() {
    return icerik;
  }

  public void setIcerik(String icerik) {
    this.icerik = icerik;
  }

  public Etkinlik baslangic(DateTime baslangic) {
    this.baslangic = baslangic;
    return this;
  }

   /**
   * Etkinliğin başlangıç zamanı. ISO8601 formatındadır.
   * @return baslangic
  **/
  @ApiModelProperty(value = "Etkinliğin başlangıç zamanı. ISO8601 formatındadır.")
  public DateTime getBaslangic() {
    return baslangic;
  }

  public void setBaslangic(DateTime baslangic) {
    this.baslangic = baslangic;
  }

  public Etkinlik bitis(DateTime bitis) {
    this.bitis = bitis;
    return this;
  }

   /**
   * Etkinliğin bitiş zamanı. ISO8601 formatındadır.
   * @return bitis
  **/
  @ApiModelProperty(value = "Etkinliğin bitiş zamanı. ISO8601 formatındadır.")
  public DateTime getBitis() {
    return bitis;
  }

  public void setBitis(DateTime bitis) {
    this.bitis = bitis;
  }

  public Etkinlik ucretliMi(Boolean ucretliMi) {
    this.ucretliMi = ucretliMi;
    return this;
  }

   /**
   * Etkinlik ücretli ise &#x60;&#x60;&#x60;true&#x60;&#x60;&#x60;, değilse &#x60;&#x60;&#x60;false&#x60;&#x60;&#x60; 
   * @return ucretliMi
  **/
  @ApiModelProperty(value = "Etkinlik ücretli ise ```true```, değilse ```false``` ")
  public Boolean getUcretliMi() {
    return ucretliMi;
  }

  public void setUcretliMi(Boolean ucretliMi) {
    this.ucretliMi = ucretliMi;
  }

  public Etkinlik afisUrl(String afisUrl) {
    this.afisUrl = afisUrl;
    return this;
  }

   /**
   * Etkinlik afiş url adresi.
   * @return afisUrl
  **/
  @ApiModelProperty(value = "Etkinlik afiş url adresi.")
  public String getAfisUrl() {
    return afisUrl;
  }

  public void setAfisUrl(String afisUrl) {
    this.afisUrl = afisUrl;
  }

  public Etkinlik durum(Integer durum) {
    this.durum = durum;
    return this;
  }

   /**
   * Muhtemel değerler;  * 1 - Onaylı  * 2 - Yayında  * 7 - İptal  * 8 - Mükerrer  * 9 - Silinmiş 
   * @return durum
  **/
  @ApiModelProperty(value = "Muhtemel değerler;  * 1 - Onaylı  * 2 - Yayında  * 7 - İptal  * 8 - Mükerrer  * 9 - Silinmiş ")
  public Integer getDurum() {
    return durum;
  }

  public void setDurum(Integer durum) {
    this.durum = durum;
  }

  public Etkinlik ozellik(EtkinlikOzellik ozellik) {
    this.ozellik = ozellik;
    return this;
  }

   /**
   * Get ozellik
   * @return ozellik
  **/
  @ApiModelProperty(value = "")
  public EtkinlikOzellik getOzellik() {
    return ozellik;
  }

  public void setOzellik(EtkinlikOzellik ozellik) {
    this.ozellik = ozellik;
  }

  public Etkinlik tur(Tur tur) {
    this.tur = tur;
    return this;
  }

   /**
   * Get tur
   * @return tur
  **/
  @ApiModelProperty(value = "")
  public Tur getTur() {
    return tur;
  }

  public void setTur(Tur tur) {
    this.tur = tur;
  }

  public Etkinlik kategori(Kategori kategori) {
    this.kategori = kategori;
    return this;
  }

   /**
   * Get kategori
   * @return kategori
  **/
  @ApiModelProperty(value = "")
  public Kategori getKategori() {
    return kategori;
  }

  public void setKategori(Kategori kategori) {
    this.kategori = kategori;
  }

  public Etkinlik mekan(Mekan mekan) {
    this.mekan = mekan;
    return this;
  }

   /**
   * Get mekan
   * @return mekan
  **/
  @ApiModelProperty(value = "")
  public Mekan getMekan() {
    return mekan;
  }

  public void setMekan(Mekan mekan) {
    this.mekan = mekan;
  }

  public Etkinlik etiketler(List<Etiket> etiketler) {
    this.etiketler = etiketler;
    return this;
  }

  public Etkinlik addEtiketlerItem(Etiket etiketlerItem) {
    if (this.etiketler == null) {
      this.etiketler = new ArrayList<Etiket>();
    }
    this.etiketler.add(etiketlerItem);
    return this;
  }

   /**
   * sd
   * @return etiketler
  **/
  @ApiModelProperty(value = "sd")
  public List<Etiket> getEtiketler() {
    return etiketler;
  }

  public void setEtiketler(List<Etiket> etiketler) {
    this.etiketler = etiketler;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Etkinlik etkinlik = (Etkinlik) o;
    return Objects.equals(this.id, etkinlik.id) &&
        Objects.equals(this.adi, etkinlik.adi) &&
        Objects.equals(this.radi, etkinlik.radi) &&
        Objects.equals(this.url, etkinlik.url) &&
        Objects.equals(this.icerik, etkinlik.icerik) &&
        Objects.equals(this.baslangic, etkinlik.baslangic) &&
        Objects.equals(this.bitis, etkinlik.bitis) &&
        Objects.equals(this.ucretliMi, etkinlik.ucretliMi) &&
        Objects.equals(this.afisUrl, etkinlik.afisUrl) &&
        Objects.equals(this.durum, etkinlik.durum) &&
        Objects.equals(this.ozellik, etkinlik.ozellik) &&
        Objects.equals(this.tur, etkinlik.tur) &&
        Objects.equals(this.kategori, etkinlik.kategori) &&
        Objects.equals(this.mekan, etkinlik.mekan) &&
        Objects.equals(this.etiketler, etkinlik.etiketler);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, adi, radi, url, icerik, baslangic, bitis, ucretliMi, afisUrl, durum, ozellik, tur, kategori, mekan, etiketler);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Etkinlik {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    adi: ").append(toIndentedString(adi)).append("\n");
    sb.append("    radi: ").append(toIndentedString(radi)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    icerik: ").append(toIndentedString(icerik)).append("\n");
    sb.append("    baslangic: ").append(toIndentedString(baslangic)).append("\n");
    sb.append("    bitis: ").append(toIndentedString(bitis)).append("\n");
    sb.append("    ucretliMi: ").append(toIndentedString(ucretliMi)).append("\n");
    sb.append("    afisUrl: ").append(toIndentedString(afisUrl)).append("\n");
    sb.append("    durum: ").append(toIndentedString(durum)).append("\n");
    sb.append("    ozellik: ").append(toIndentedString(ozellik)).append("\n");
    sb.append("    tur: ").append(toIndentedString(tur)).append("\n");
    sb.append("    kategori: ").append(toIndentedString(kategori)).append("\n");
    sb.append("    mekan: ").append(toIndentedString(mekan)).append("\n");
    sb.append("    etiketler: ").append(toIndentedString(etiketler)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

