/*
 * Etkinlik.io API
 * Tüm etkinlikleri toplamayı, kategorize etmeyi ve ilgili kişilere duyurmayı amaç edinmiş bir projedir. Bu API dokümantasyonu ile bir çok kaynaktan ve organizatörden beslenerek bir araya getirdiğimiz etkinlik içeriğine entegre olarak uygulamalar geliştirebilirsiniz. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Mekan;
import io.swagger.client.model.Sayfalama;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse2001
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-29T05:46:48.775Z")
public class InlineResponse2001 {
  @SerializedName("sayfalama")
  private Sayfalama sayfalama = null;

  @SerializedName("kayitlar")
  private List<Mekan> kayitlar = null;

  public InlineResponse2001 sayfalama(Sayfalama sayfalama) {
    this.sayfalama = sayfalama;
    return this;
  }

   /**
   * Get sayfalama
   * @return sayfalama
  **/
  @ApiModelProperty(value = "")
  public Sayfalama getSayfalama() {
    return sayfalama;
  }

  public void setSayfalama(Sayfalama sayfalama) {
    this.sayfalama = sayfalama;
  }

  public InlineResponse2001 kayitlar(List<Mekan> kayitlar) {
    this.kayitlar = kayitlar;
    return this;
  }

  public InlineResponse2001 addKayitlarItem(Mekan kayitlarItem) {
    if (this.kayitlar == null) {
      this.kayitlar = new ArrayList<Mekan>();
    }
    this.kayitlar.add(kayitlarItem);
    return this;
  }

   /**
   * Get kayitlar
   * @return kayitlar
  **/
  @ApiModelProperty(value = "")
  public List<Mekan> getKayitlar() {
    return kayitlar;
  }

  public void setKayitlar(List<Mekan> kayitlar) {
    this.kayitlar = kayitlar;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001 inlineResponse2001 = (InlineResponse2001) o;
    return Objects.equals(this.sayfalama, inlineResponse2001.sayfalama) &&
        Objects.equals(this.kayitlar, inlineResponse2001.kayitlar);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sayfalama, kayitlar);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001 {\n");
    
    sb.append("    sayfalama: ").append(toIndentedString(sayfalama)).append("\n");
    sb.append("    kayitlar: ").append(toIndentedString(kayitlar)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

