/*
 * Etkinlik.io API
 * Tüm etkinlikleri toplamayı, kategorize etmeyi ve ilgili kişilere duyurmayı amaç edinmiş bir projedir. Bu API dokümantasyonu ile bir çok kaynaktan ve organizatörden beslenerek bir araya getirdiğimiz etkinlik içeriğine entegre olarak uygulamalar geliştirebilirsiniz. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MekanIlce;
import io.swagger.client.model.Semt;
import java.io.IOException;

/**
 * Mekan
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-29T05:46:48.775Z")
public class Mekan {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("adi")
  private String adi = null;

  @SerializedName("radi")
  private String radi = null;

  @SerializedName("adresi")
  private String adresi = null;

  @SerializedName("lat")
  private String lat = null;

  @SerializedName("lng")
  private String lng = null;

  @SerializedName("telefon")
  private String telefon = null;

  @SerializedName("websitesi")
  private String websitesi = null;

  @SerializedName("facebook")
  private String facebook = null;

  @SerializedName("twitter")
  private String twitter = null;

  @SerializedName("ilce")
  private MekanIlce ilce = null;

  @SerializedName("semt")
  private Semt semt = null;

  public Mekan id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Mekan id bilgisi.
   * @return id
  **/
  @ApiModelProperty(value = "Mekan id bilgisi.")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Mekan adi(String adi) {
    this.adi = adi;
    return this;
  }

   /**
   * Mekan adı bilgisi.
   * @return adi
  **/
  @ApiModelProperty(value = "Mekan adı bilgisi.")
  public String getAdi() {
    return adi;
  }

  public void setAdi(String adi) {
    this.adi = adi;
  }

  public Mekan radi(String radi) {
    this.radi = radi;
    return this;
  }

   /**
   * Mekan radı (slug) bilgisi.
   * @return radi
  **/
  @ApiModelProperty(value = "Mekan radı (slug) bilgisi.")
  public String getRadi() {
    return radi;
  }

  public void setRadi(String radi) {
    this.radi = radi;
  }

  public Mekan adresi(String adresi) {
    this.adresi = adresi;
    return this;
  }

   /**
   * Mekan adres bilgisi.
   * @return adresi
  **/
  @ApiModelProperty(value = "Mekan adres bilgisi.")
  public String getAdresi() {
    return adresi;
  }

  public void setAdresi(String adresi) {
    this.adresi = adresi;
  }

  public Mekan lat(String lat) {
    this.lat = lat;
    return this;
  }

   /**
   * Mekanın konum bilgisindeki latitude kısmıdır.
   * @return lat
  **/
  @ApiModelProperty(value = "Mekanın konum bilgisindeki latitude kısmıdır.")
  public String getLat() {
    return lat;
  }

  public void setLat(String lat) {
    this.lat = lat;
  }

  public Mekan lng(String lng) {
    this.lng = lng;
    return this;
  }

   /**
   * Mekanın konum bilgisindeki longitude kısmıdır
   * @return lng
  **/
  @ApiModelProperty(value = "Mekanın konum bilgisindeki longitude kısmıdır")
  public String getLng() {
    return lng;
  }

  public void setLng(String lng) {
    this.lng = lng;
  }

  public Mekan telefon(String telefon) {
    this.telefon = telefon;
    return this;
  }

   /**
   * Mekanın telefon numarası.
   * @return telefon
  **/
  @ApiModelProperty(value = "Mekanın telefon numarası.")
  public String getTelefon() {
    return telefon;
  }

  public void setTelefon(String telefon) {
    this.telefon = telefon;
  }

  public Mekan websitesi(String websitesi) {
    this.websitesi = websitesi;
    return this;
  }

   /**
   * Mekanın websitesi adresi.
   * @return websitesi
  **/
  @ApiModelProperty(value = "Mekanın websitesi adresi.")
  public String getWebsitesi() {
    return websitesi;
  }

  public void setWebsitesi(String websitesi) {
    this.websitesi = websitesi;
  }

  public Mekan facebook(String facebook) {
    this.facebook = facebook;
    return this;
  }

   /**
   * Mekanın facebook adresi.
   * @return facebook
  **/
  @ApiModelProperty(value = "Mekanın facebook adresi.")
  public String getFacebook() {
    return facebook;
  }

  public void setFacebook(String facebook) {
    this.facebook = facebook;
  }

  public Mekan twitter(String twitter) {
    this.twitter = twitter;
    return this;
  }

   /**
   * Mekanın twitter adresi.
   * @return twitter
  **/
  @ApiModelProperty(value = "Mekanın twitter adresi.")
  public String getTwitter() {
    return twitter;
  }

  public void setTwitter(String twitter) {
    this.twitter = twitter;
  }

  public Mekan ilce(MekanIlce ilce) {
    this.ilce = ilce;
    return this;
  }

   /**
   * Get ilce
   * @return ilce
  **/
  @ApiModelProperty(value = "")
  public MekanIlce getIlce() {
    return ilce;
  }

  public void setIlce(MekanIlce ilce) {
    this.ilce = ilce;
  }

  public Mekan semt(Semt semt) {
    this.semt = semt;
    return this;
  }

   /**
   * Get semt
   * @return semt
  **/
  @ApiModelProperty(value = "")
  public Semt getSemt() {
    return semt;
  }

  public void setSemt(Semt semt) {
    this.semt = semt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Mekan mekan = (Mekan) o;
    return Objects.equals(this.id, mekan.id) &&
        Objects.equals(this.adi, mekan.adi) &&
        Objects.equals(this.radi, mekan.radi) &&
        Objects.equals(this.adresi, mekan.adresi) &&
        Objects.equals(this.lat, mekan.lat) &&
        Objects.equals(this.lng, mekan.lng) &&
        Objects.equals(this.telefon, mekan.telefon) &&
        Objects.equals(this.websitesi, mekan.websitesi) &&
        Objects.equals(this.facebook, mekan.facebook) &&
        Objects.equals(this.twitter, mekan.twitter) &&
        Objects.equals(this.ilce, mekan.ilce) &&
        Objects.equals(this.semt, mekan.semt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, adi, radi, adresi, lat, lng, telefon, websitesi, facebook, twitter, ilce, semt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Mekan {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    adi: ").append(toIndentedString(adi)).append("\n");
    sb.append("    radi: ").append(toIndentedString(radi)).append("\n");
    sb.append("    adresi: ").append(toIndentedString(adresi)).append("\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    lng: ").append(toIndentedString(lng)).append("\n");
    sb.append("    telefon: ").append(toIndentedString(telefon)).append("\n");
    sb.append("    websitesi: ").append(toIndentedString(websitesi)).append("\n");
    sb.append("    facebook: ").append(toIndentedString(facebook)).append("\n");
    sb.append("    twitter: ").append(toIndentedString(twitter)).append("\n");
    sb.append("    ilce: ").append(toIndentedString(ilce)).append("\n");
    sb.append("    semt: ").append(toIndentedString(semt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

