/*
 * Etkinlik.io API
 * Tüm etkinlikleri toplamayı, kategorize etmeyi ve ilgili kişilere duyurmayı amaç edinmiş bir projedir. Bu API dokümantasyonu ile bir çok kaynaktan ve organizatörden beslenerek bir araya getirdiğimiz etkinlik içeriğine entegre olarak uygulamalar geliştirebilirsiniz. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MekanIlceSehir;
import java.io.IOException;

/**
 * Mekanın ilçe bilgisi
 */
@ApiModel(description = "Mekanın ilçe bilgisi")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-29T05:46:48.775Z")
public class MekanIlce {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("adi")
  private String adi = null;

  @SerializedName("sehir")
  private MekanIlceSehir sehir = null;

  public MekanIlce id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * İlçenin id bilgisi.
   * @return id
  **/
  @ApiModelProperty(value = "İlçenin id bilgisi.")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public MekanIlce adi(String adi) {
    this.adi = adi;
    return this;
  }

   /**
   * İlçenin adı bilgisi.
   * @return adi
  **/
  @ApiModelProperty(value = "İlçenin adı bilgisi.")
  public String getAdi() {
    return adi;
  }

  public void setAdi(String adi) {
    this.adi = adi;
  }

  public MekanIlce sehir(MekanIlceSehir sehir) {
    this.sehir = sehir;
    return this;
  }

   /**
   * Get sehir
   * @return sehir
  **/
  @ApiModelProperty(value = "")
  public MekanIlceSehir getSehir() {
    return sehir;
  }

  public void setSehir(MekanIlceSehir sehir) {
    this.sehir = sehir;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MekanIlce mekanIlce = (MekanIlce) o;
    return Objects.equals(this.id, mekanIlce.id) &&
        Objects.equals(this.adi, mekanIlce.adi) &&
        Objects.equals(this.sehir, mekanIlce.sehir);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, adi, sehir);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MekanIlce {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    adi: ").append(toIndentedString(adi)).append("\n");
    sb.append("    sehir: ").append(toIndentedString(sehir)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

