/*
 * Etkinlik.io API
 * Tüm etkinlikleri toplamayı, kategorize etmeyi ve ilgili kişilere duyurmayı amaç edinmiş bir projedir. Bu API dokümantasyonu ile bir çok kaynaktan ve organizatörden beslenerek bir araya getirdiğimiz etkinlik içeriğine entegre olarak uygulamalar geliştirebilirsiniz. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Sayfalama
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-29T05:46:48.775Z")
public class Sayfalama {
  @SerializedName("toplamKayit")
  private Integer toplamKayit = null;

  @SerializedName("toplamSayfa")
  private Integer toplamSayfa = null;

  @SerializedName("sayfa")
  private Integer sayfa = null;

  @SerializedName("adet")
  private Integer adet = null;

  public Sayfalama toplamKayit(Integer toplamKayit) {
    this.toplamKayit = toplamKayit;
    return this;
  }

   /**
   * Get toplamKayit
   * @return toplamKayit
  **/
  @ApiModelProperty(value = "")
  public Integer getToplamKayit() {
    return toplamKayit;
  }

  public void setToplamKayit(Integer toplamKayit) {
    this.toplamKayit = toplamKayit;
  }

  public Sayfalama toplamSayfa(Integer toplamSayfa) {
    this.toplamSayfa = toplamSayfa;
    return this;
  }

   /**
   * Get toplamSayfa
   * @return toplamSayfa
  **/
  @ApiModelProperty(value = "")
  public Integer getToplamSayfa() {
    return toplamSayfa;
  }

  public void setToplamSayfa(Integer toplamSayfa) {
    this.toplamSayfa = toplamSayfa;
  }

  public Sayfalama sayfa(Integer sayfa) {
    this.sayfa = sayfa;
    return this;
  }

   /**
   * Get sayfa
   * @return sayfa
  **/
  @ApiModelProperty(value = "")
  public Integer getSayfa() {
    return sayfa;
  }

  public void setSayfa(Integer sayfa) {
    this.sayfa = sayfa;
  }

  public Sayfalama adet(Integer adet) {
    this.adet = adet;
    return this;
  }

   /**
   * Get adet
   * @return adet
  **/
  @ApiModelProperty(value = "")
  public Integer getAdet() {
    return adet;
  }

  public void setAdet(Integer adet) {
    this.adet = adet;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sayfalama sayfalama = (Sayfalama) o;
    return Objects.equals(this.toplamKayit, sayfalama.toplamKayit) &&
        Objects.equals(this.toplamSayfa, sayfalama.toplamSayfa) &&
        Objects.equals(this.sayfa, sayfalama.sayfa) &&
        Objects.equals(this.adet, sayfalama.adet);
  }

  @Override
  public int hashCode() {
    return Objects.hash(toplamKayit, toplamSayfa, sayfa, adet);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sayfalama {\n");
    
    sb.append("    toplamKayit: ").append(toIndentedString(toplamKayit)).append("\n");
    sb.append("    toplamSayfa: ").append(toIndentedString(toplamSayfa)).append("\n");
    sb.append("    sayfa: ").append(toIndentedString(sayfa)).append("\n");
    sb.append("    adet: ").append(toIndentedString(adet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

