/*
 * Etkinlik.io API
 * Tüm etkinlikleri toplamayı, kategorize etmeyi ve ilgili kişilere duyurmayı amaç edinmiş bir projedir. Bu API dokümantasyonu ile bir çok kaynaktan ve organizatörden beslenerek bir araya getirdiğimiz etkinlik içeriğine entegre olarak uygulamalar geliştirebilirsiniz. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Tur
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-29T05:46:48.775Z")
public class Tur {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("adi")
  private String adi = null;

  @SerializedName("radi")
  private String radi = null;

  public Tur id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Tür id bilgisi.
   * @return id
  **/
  @ApiModelProperty(value = "Tür id bilgisi.")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Tur adi(String adi) {
    this.adi = adi;
    return this;
  }

   /**
   * Tür adı bilgisi.
   * @return adi
  **/
  @ApiModelProperty(value = "Tür adı bilgisi.")
  public String getAdi() {
    return adi;
  }

  public void setAdi(String adi) {
    this.adi = adi;
  }

  public Tur radi(String radi) {
    this.radi = radi;
    return this;
  }

   /**
   * Tür radı (slug) bilgisi.
   * @return radi
  **/
  @ApiModelProperty(value = "Tür radı (slug) bilgisi.")
  public String getRadi() {
    return radi;
  }

  public void setRadi(String radi) {
    this.radi = radi;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tur tur = (Tur) o;
    return Objects.equals(this.id, tur.id) &&
        Objects.equals(this.adi, tur.adi) &&
        Objects.equals(this.radi, tur.radi);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, adi, radi);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tur {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    adi: ").append(toIndentedString(adi)).append("\n");
    sb.append("    radi: ").append(toIndentedString(radi)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

